[DEFAULT]
# Plex API Key - https://support.plex.tv/articles/204059436-finding-an-authentication-token-x-plex-token/ 
PLEX_API_KEY=insert_your_plex_api_key_here
# Plex URL/IP address
PLEX_URL=insert_your_plex_ip_here
# Plex Port (default is 32400)
PLEX_PORT=32400
# Tautulli URL/IP address
TAUTULLI_URL=insert_your_tautulli_ip_here
# Tautulli Port (default is 8181)
TAUTULLI_PORT=8181
# Tautulli API Key - Go into Tautulli Settings > Web Interface > Show Advanced > API Key is at the bottom
TAUTULLI_API_KEY=insert_your_tautulli_api_key_here